[package]
name = "jwt-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonwebtoken = "9.3.1"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
dotenv = "0.15"
